//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE_ManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagementContextEntities : DbContext
    {
        public ManagementContextEntities()
            : base("name=ManagementContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Kind> Kinds { get; set; }
        public virtual DbSet<KindProcess> KindProcesses { get; set; }
        public virtual DbSet<KPN> KPNs { get; set; }
        public virtual DbSet<LabelRule> LabelRules { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MeProduct> MeProducts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductTransaction> ProductTransactions { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    }
}
