//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE_ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeProduct()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string ProdName { get; set; }
        public int KindID { get; set; }
        public int KindProcessID { get; set; }
        public int CustomerID { get; set; }
        public int SupplierID { get; set; }
        public string Opid { get; set; }
        public int Quantity { get; set; }
        public int ShiftTime { get; set; }
        public bool IsStock { get; set; }
        public bool IsReturnMe { get; set; }
        public bool Pb { get; set; }
        public string Image { get; set; }
        public string ComList { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Spare3 { get; set; }
        public string Spare4 { get; set; }
        public string Spare5 { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Kind Kind { get; set; }
        public virtual KindProcess KindProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
