//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE_ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldProduct
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string NumberID { get; set; }
        public string Location { get; set; }
        public string ProdName { get; set; }
        public string Files { get; set; }
        public string Customer { get; set; }
        public string Status { get; set; }
        public string Qty { get; set; }
        public string StatusOnToolRoom { get; set; }
        public string KPN { get; set; }
        public string KindProcess { get; set; }
        public Nullable<bool> IsDone { get; set; }
    }
}
