CREATE TABLE [dbo].[Kind](
	[ID]			INT				NOT NULL,
	[Name]			VARCHAR(100)	NOT NULL,
	[LabelRule]		VARCHAR(100)	NOT NULL,
	[Spare1]		VARCHAR(100)	NULL,
	[Spare2]		VARCHAR(100)	NULL,
	[Spare3]		VARCHAR(100)	NULL,
	[Spare4]		VARCHAR(100)	NULL,
	[Spare5]		VARCHAR(100)	NULL,
	CONSTRAINT	[PK_Kind] PRIMARY KEY CLUSTERED ([ID] ASC)
);
